// <auto-generated />
using System;
using BancoCitacoes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoCitacoes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604212628_Tercial")]
    partial class Tercial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BancoCitacoes.Models.BancoFrases", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Autores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BancoFrases");
                });
#pragma warning restore 612, 618
        }
    }
}
